<a href="https://colab.research.google.com/github/utk1801/Are-you-sure-to-Insure-/blob/master/Greyatom_Hack_a_thon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.read_csv('train.csv')

          ID Agency    Agency Type  ... Commision (in value) Gender    Age
0       3433    CWT  Travel Agency  ...                17.82    NaN   31.0
1       4339    EPX  Travel Agency  ...                 0.00    NaN   36.0
2      34590    CWT  Travel Agency  ...                11.88    NaN   75.0
3      55816    EPX  Travel Agency  ...                 0.00    NaN   32.0
4      13816    EPX  Travel Agency  ...                 0.00    NaN   29.0
5      50349    CWT  Travel Agency  ...                29.70    NaN   36.0
6       9921    JZI       Airlines  ...                24.15      F   26.0
7      21923    JZI       Airlines  ...                 9.10      M   60.0
8       2236    CWT  Travel Agency  ...                11.88    NaN   57.0
9      14486    EPX  Travel Agency  ...                 0.00    NaN   47.0
10      5470    EPX  Travel Agency  ...                 0.00    NaN   36.0
11      7902    EPX  Travel Agency  ...                 0.00    NaN   50.0
12     38182    EPX  Travel Agency  ...                 0.00    NaN   36.0
13     31023    C2B       Airlines  ...                 4.50      M   42.0
14     39039    CWT  Travel Agency  ...                23.76    NaN   45.0
15     42497    EPX  Travel Agency  ...                 0.00    NaN   36.0
16     23516    SSI       Airlines  ...                 1.96    NaN   48.0
17     43173    EPX  Travel Agency  ...                 0.00    NaN   36.0
18     21158    CSR  Travel Agency  ...                 9.57      F   26.0
19      3623    CWT  Travel Agency  ...                23.76    NaN   31.0
20     38057    EPX  Travel Agency  ...                 0.00    NaN   35.0
21      8024    EPX  Travel Agency  ...                 0.00    NaN   36.0
22     52345    EPX  Travel Agency  ...                 0.00    NaN   36.0
23      9961    CWT  Travel Agency  ...                29.70    NaN   32.0
24     27257    JZI       Airlines  ...                 6.30      F   28.0
25     54796    CWT  Travel Agency  ...                17.82    NaN   23.0
26      1141    EPX  Travel Agency  ...                 0.00    NaN   36.0
27     17595    EPX  Travel Agency  ...                 0.00    NaN   36.0
28     10098    EPX  Travel Agency  ...                 0.00    NaN   36.0
29     47578    C2B       Airlines  ...                15.50      F   30.0
...      ...    ...            ...  ...                  ...    ...    ...
26268  36071    JZI       Airlines  ...                 6.30      F   26.0
26269   6052    EPX  Travel Agency  ...                 0.00    NaN   37.0
26270  28186    EPX  Travel Agency  ...                 0.00    NaN   36.0
26271   4064    C2B       Airlines  ...                 8.50      M   40.0
26272  30477    C2B       Airlines  ...                15.88      F   21.0
26273  21506    EPX  Travel Agency  ...                 0.00    NaN   36.0
26274  40275    EPX  Travel Agency  ...                 0.00    NaN   47.0
26275  45249    EPX  Travel Agency  ...                 0.00    NaN   47.0
26276  40220    C2B       Airlines  ...                 5.25      F   29.0
26277  56973    JZI       Airlines  ...                 6.30      M   58.0
26278  12420    EPX  Travel Agency  ...                 0.00    NaN   45.0
26279  37717    JZI       Airlines  ...                 7.70      M   65.0
26280  55635    EPX  Travel Agency  ...                 0.00    NaN   36.0
26281  48234    C2B       Airlines  ...                54.00      F   57.0
26282  24522    JZI       Airlines  ...                 9.10      F   54.0
26283  46488    JZI       Airlines  ...                 6.30    NaN  118.0
26284  44475    EPX  Travel Agency  ...                 0.00    NaN   36.0
26285  18722    EPX  Travel Agency  ...                 0.00    NaN   36.0
26286  34983    EPX  Travel Agency  ...                 0.00    NaN   36.0
26287  53675    EPX  Travel Agency  ...                 0.00    NaN   36.0
26288  25844    JZI       Airlines  ...                14.00      F   17.0
26289  43493    C2B       Airlines  ...                 5.25      F   26.0
26290  55403    CWT  Travel Agency  ...                47.52    NaN   58.0
26291  55709    JZI       Airlines  ...                 7.70      M   45.0
26292  33459    CWT  Travel Agency  ...                11.88    NaN   36.0
26293  19045    CWT  Travel Agency  ...                11.88    NaN   31.0
26294  34685    EPX  Travel Agency  ...                 0.00    NaN   42.0
26295  30768    EPX  Travel Agency  ...                 0.00    NaN   38.0
26296  17789    CWT  Travel Agency  ...                35.64    NaN   29.0
26297  57892    JZI       Airlines  ...                  NaN    NaN    NaN

[26298 rows x 12 columns]

In [0]:
data=pd.read_csv('train.csv')

In [3]:
data.describe()

                 ID         Claim  ...  Commision (in value)           Age
count  50553.000000  50553.000000  ...           50553.00000  50553.000000
mean   31679.740134      0.014658  ...               9.83809     40.011236
std    18288.265350      0.120180  ...              19.91004     14.076566
min        0.000000      0.000000  ...               0.00000      0.000000
25%    15891.000000      0.000000  ...               0.00000     35.000000
50%    31657.000000      0.000000  ...               0.00000     36.000000
75%    47547.000000      0.000000  ...              11.55000     44.000000
max    63325.000000      1.000000  ...             283.50000    118.000000

[8 rows x 6 columns]

In [4]:
data.size

606636

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50553 entries, 0 to 50552
Data columns (total 12 columns):
ID                      50553 non-null int64
Agency                  50553 non-null object
Agency Type             50553 non-null object
Distribution Channel    50553 non-null object
Product Name            50553 non-null object
Claim                   50553 non-null int64
Duration                50553 non-null int64
Destination             50553 non-null object
Net Sales               50553 non-null float64
Commision (in value)    50553 non-null float64
Gender                  14600 non-null object
Age                     50553 non-null int64
dtypes: float64(2), int64(4), object(6)
memory usage: 4.6+ MB

In [8]:
data.shape

(50553, 12)